name: mcp_dart
description: "A new Flutter project."
publish_to: 'none' 
version: 1.1.0+1
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.35.1"
dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true
  assets:
    - .env    
